import type { RiftexContext } from '../context/context.ts'

/**
 * RFC 7807 Problem Details for HTTP APIs.
 *
 * The five standard members are reserved by the spec; arbitrary additional
 * extension members are permitted via the index signature. See
 * https://datatracker.ietf.org/doc/html/rfc7807#section-3.1.
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type. When dereferenced it
   * SHOULD provide human-readable documentation. Default per spec is
   * `'about:blank'`, indicating that no specific problem-type URL exists
   * (in which case `title` is conventionally the HTTP status reason phrase).
   */
  type: string

  /**
   * A short, human-readable summary of the problem type. SHOULD NOT change
   * from occurrence to occurrence (use `detail` for instance-specific info).
   */
  title: string

  /** HTTP status code generated by the origin server. */
  status: number

  /** Human-readable explanation specific to this occurrence of the problem. */
  detail?: string

  /** A URI reference identifying the specific occurrence of the problem. */
  instance?: string

  /** RFC 7807 permits arbitrary extension members. */
  [key: string]: unknown
}

/** Options accepted by `riftex.problemDetails(...)`. */
export interface ProblemDetailsOptions {
  /**
   * Prefix used when constructing the `type` URI from an error's `code`.
   * Example: `'https://api.example.com/errors/'` + `NOT_FOUND` →
   * `'https://api.example.com/errors/not-found'`.
   *
   * Default `'about:blank'` (per spec — no problem-specific docs URL).
   */
  typeBaseUrl?: string

  /**
   * If true, attaches the error's `stack` as an extension member. Useful in
   * development; never enable in production — stack traces leak source paths
   * and internal structure. Default `false`.
   */
  includeStack?: boolean

  /**
   * Override how the `instance` URI is derived. Default returns `ctx.path`.
   * Return `undefined` to omit the field entirely.
   */
  instance?: (ctx: RiftexContext) => string | undefined
}

/** Options after defaults have been applied. Internal use. */
export interface ResolvedProblemDetailsOptions {
  typeBaseUrl: string
  includeStack: boolean
  instance: (ctx: RiftexContext) => string | undefined
}
